var ENTRANCES = [
  {name:"Links House", world:"lw", left:57.5, top:72.0},
  {name:"Bonk Fairy (Light)", world:"lw", left:49.0, top:67.0},
  {name:"Dam", world:"lw", left:49.1, top:96.0},
  {name:"Cave 45", world:"lw", left:28.0, top:84.0},
  {name:"Potion Shop", world:"lw", left:81.4, top:35.0},
  {name:"Waterfall of Wishing", world:"lw", left:91.4, top:17.0},
  {name:"Light Hype Fairy", world:"lw", left:62.0, top:80.0},
  {name:"Hyrule Castle Entrance (South)", world:"lw", left:52.4, top:46.0},
  {name:"Hyrule Castle Entrance (West)", world:"lw", left:46.4, top:41.0},
  {name:"Hyrule Castle Entrance (East)", world:"lw", left:58.5, top:41.0},
  {name:"Agahnims Tower", world:"lw", left:52.4, top:40.0},
  {name:"Hyrule Castle Secret Entrance Stairs", world:"lw", left:56.4, top:44.0},
  {name:"Hyrule Castle Secret Entrance Drop", world:"lw", left:61.0, top:42.5},
  {name:"Sanctuary", world:"lw", left:48.9, top:28.0},
  {name:"Bonk Rock Cave", world:"lw", left:41.5, top:31.5},
  {name:"Sanctuary Grave", world:"lw", left:54.9, top:31.5},
  {name:"Graveyard Cave", world:"lw", left:60.1, top:29.9},
  {name:"Kings Grave", world:"lw", left:63.5, top:31.5},
  {name:"North Fairy Cave", world:"lw", left:69.5, top:30.5},
  {name:"North Fairy Cave Drop", world:"lw", left:66.0, top:32.0},
  {name:"Lost Woods Gamble", world:"lw", left:20.2, top:3.1},
  {name:"Lost Woods Hideout Drop", world:"lw", left:20.6, top:13.2},
  {name:"Lost Woods Hideout Stump", world:"lw", left:20.0, top:16.0},
  {name:"Lumberjack House", world:"lw", left:36.7, top:7.4},
  {name:"Lumberjack Tree Cave", world:"lw", left:35.5, top:4.5},
  {name:"Lumberjack Tree Tree", world:"lw", left:31.4, top:9.0},
  {name:"Old Man Cave (West)", world:"lw", left:37.5, top:19.7},
  {name:"Fortune Teller (Light)", world:"lw", left:20.6, top:33.0},
  {name:"Kakariko Well Drop", world:"lw", left:4.0, top:43.0},
  {name:"Kakariko Well Cave", world:"lw", left:7.0, top:44.0},
  {name:"Blinds Hideout", world:"lw", left:15.5, top:43.0},
  {name:"Elder House (West)", world:"lw", left:17.9, top:43.0},
  {name:"Elder House (East)", world:"lw", left:20.1, top:43.0},
  {name:"Snitch Lady (West)", world:"lw", left:7.4, top:48.0},
  {name:"Snitch Lady (East)", world:"lw", left:22.8, top:49.0},
  {name:"Chicken House", world:"lw", left:12.0, top:55.0},
  {name:"Sick Kids House", world:"lw", left:17.6, top:55.0},
  {name:"Bush Covered House", world:"lw", left:22.6, top:55.0},
  {name:"Light World Bomb Hut", world:"lw", left:4.6, top:61.0},
  {name:"Kakariko Shop", world:"lw", left:13.4, top:59.0},
  {name:"Tavern North", world:"lw", left:18.2, top:58.0},
  {name:"Tavern (Front)", world:"lw", left:18.2, top:61.0},
  {name:"Blacksmiths Hut", world:"lw", left:32.7, top:55.5},
  {name:"Bat Cave Cave", world:"lw", left:34.7, top:58.5},
  {name:"Bat Cave Drop", world:"lw", left:36.1, top:56.5},
  {name:"Library", world:"lw", left:16.8, top:67.0},
  {name:"Two Brothers House (West)", world:"lw", left:13.5, top:73.5},
  {name:"Two Brothers House (East)", world:"lw", left:17.5, top:73.5},
  {name:"Kakariko Gamble Game", world:"lw", left:24.3, top:71.8},
  {name:"Eastern Palace", world:"lw", left:98.7, top:41.5},
  {name:"Sahasrahlas Hut", world:"lw", left:84.5, top:46.0},
  {name:"Lake Hylia Fairy", world:"lw", left:84.0, top:65.4},
  {name:"Long Fairy Cave", world:"lw", left:99.2, top:71.0},
  {name:"Desert Palace Entrance (South)", world:"lw", left:8.8, top:82.0},
  {name:"Desert Palace Entrance (West)", world:"lw", left:5.0, top:81.0},
  {name:"Desert Palace Entrance (East)", world:"lw", left:12.6, top:81.0},
  {name:"Desert Palace Entrance (North)", world:"lw", left:8.8, top:78.0},
  {name:"Checkerboard Cave", world:"lw", left:19.0, top:79.0},
  {name:"Aginahs Cave", world:"lw", left:23.1, top:84.5},
  {name:"Desert Fairy", world:"lw", left:30.9, top:91.5},
  {name:"50 Rupee Cave", world:"lw", left:34.1, top:97.5},
  {name:"Lake Hylia Shop", world:"lw", left:74.4, top:78.0},
  {name:"Lake Hylia Fortune Teller", world:"lw", left:66.4, top:81.0},
  {name:"Mini Moldorm Cave", world:"lw", left:68.3, top:96.5},
  {name:"Capacity Upgrade", world:"lw", left:82.3, top:87.5},
  {name:"Ice Rod Cave", world:"lw", left:92.1, top:79.5},
  {name:"Good Bee Cave", world:"lw", left:94.9, top:79.5},
  {name:"20 Rupee Cave", world:"lw", left:93.3, top:81.5},
  {name:"Tower of Hera", world:"lw", left:58.9, top:5.0},
  {name:"Spectacle Rock Cave Peak", world:"lw", left:47.0, top:15.0},
  {name:"Spectacle Rock Cave (Bottom)", world:"lw", left:51.7, top:16.0},
  {name:"Spectacle Rock Cave", world:"lw", left:51.7, top:13.0},
  {name:"Old Man Cave (East)", world:"lw", left:41.6, top:20.0},
  {name:"Death Mountain Return Cave (East)", world:"lw", left:40.8, top:14.0},
  {name:"Death Mountain Return Cave (West)", world:"lw", left:37.4, top:16.0},
  {name:"Old Man House (Bottom)", world:"lw", left:46.6, top:25.0},
  {name:"Old Man House (Top)", world:"lw", left:55.0, top:17.4},
  {name:"Paradox Cave (Top)", world:"lw", left:88.1, top:8.9},
  {name:"Paradox Cave (Middle)", world:"lw", left:87.6, top:23.0},
  {name:"Paradox Cave (Bottom)", world:"lw", left:87.6, top:16.0},
  {name:"Spiral Cave", world:"lw", left:81.0, top:10.0},
  {name:"Spiral Cave (Bottom)", world:"lw", left:81.0, top:14.0},
  {name:"Hookshot Fairy", world:"lw", left:85.0, top:16.0},
  {name:"Fairy Ascension Cave (Top)", world:"lw", left:83.2, top:12.4},
  {name:"Fairy Ascension Cave (Bottom)", world:"lw", left:83.2, top:14.9},
  {name:"Mimic Cave", world:"lw", left:85.8, top:10.0},
  {name:"Big Bomb Shop", world:"dw", left:56.0, top:72.0},
  {name:"Bonk Fairy (Dark)", world:"dw", left:49.0, top:67.0},
  {name:"Hype Cave", world:"dw", left:62.0, top:80.0},
  {name:"Swamp Palace", world:"dw", left:48.4, top:96.0},
  {name:"Dark Sanctuary Hint", world:"dw", left:47.4, top:28.0},
  {name:"Red Shield Shop", world:"dw", left:34.8, top:46.6},
  {name:"Dark Potion Shop", world:"dw", left:81.4, top:35.0},
  {name:"Pyramid Hole", world:"dw", left:51.4, top:42.0},
  {name:"Pyramid Fairy", world:"dw", left:48.0, top:50.0},
  {name:"Pyramid Exit", world:"dw", left:44.8, top:50.0},
  {name:"Skull Woods Final Section", world:"dw", left:5.4, top:6.5},
  {name:"Skull Woods Second Section Door (West)", world:"dw", left:7.4, top:14.0},
  {name:"Skull Woods Second Section Hole", world:"dw", left:13.4, top:10.0},
  {name:"Skull Woods Second Section Door (East)", world:"dw", left:15.6, top:16.0},
  {name:"Skull Woods First Section Hole (West)", world:"dw", left:17.0, top:19.0},
  {name:"Skull Woods First Section Hole (North)", world:"dw", left:20.4, top:13.5},
  {name:"Skull Woods First Section Door", world:"dw", left:19.4, top:16.0},
  {name:"Skull Woods First Section Hole (East)", world:"dw", left:21.6, top:18.0},
  {name:"Dark Lumberjack Shop", world:"dw", left:35.0, top:6.7},
  {name:"Bumper Cave (Bottom)", world:"dw", left:37.0, top:19.0},
  {name:"Fortune Teller (Dark)", world:"dw", left:20.2, top:33.0},
  {name:"Chest Game", world:"dw", left:6.0, top:47.0},
  {name:"Thieves Town", world:"dw", left:14.0, top:49.0},
  {name:"C-Shaped House", world:"dw", left:22.0, top:49.0},
  {name:"Dark World Shop", world:"dw", left:22.0, top:54.0},
  {name:"Brewery", world:"dw", left:12.6, top:59.0},
  {name:"Hammer Peg Cave", world:"dw", left:33.0, top:62.0},
  {name:"Archery Game", world:"dw", left:23.0, top:71.0},
  {name:"Palace of Darkness", world:"dw", left:97.2, top:41.0},
  {name:"Palace of Darkness Hint", world:"dw", left:86.6, top:52.0},
  {name:"Dark Lake Hylia Fairy", world:"dw", left:84.0, top:65.7},
  {name:"East Dark World Hint", world:"dw", left:99.2, top:71.0},
  {name:"Ice Palace", world:"dw", left:81.0, top:87.0},
  {name:"Dark Lake Hylia Shop", world:"dw", left:66.6, top:81.0},
  {name:"Dark Lake Hylia Ledge Fairy", world:"dw", left:90.6, top:78.0},
  {name:"Dark Lake Hylia Ledge Hint", world:"dw", left:93.4, top:78.0},
  {name:"Dark Lake Hylia Ledge Spike Cave", world:"dw", left:91.8, top:80.0},
  {name:"Misery Mire", world:"dw", left:8.8, top:84.0},
  {name:"Mire Shed", world:"dw", left:5.4, top:81.0},
  {name:"Mire Fairy", world:"dw", left:12.6, top:81.0},
  {name:"Mire Hint", world:"dw", left:21.2, top:83.0},
  {name:"Ganons Tower", world:"dw", left:57.6, top:5.0},
  {name:"Spike Cave", world:"dw", left:58.8, top:16.0},
  {name:"Bumper Cave (Top)", world:"dw", left:37.6, top:16.0},
  {name:"Dark Death Mountain Fairy", world:"dw", left:41.6, top:20.0},
  {name:"Hookshot Cave Back Entrance", world:"dw", left:81.6, top:3.0},
  {name:"Hookshot Cave", world:"dw", left:84.4, top:7.5},
  {name:"Superbunny Cave (Top)", world:"dw", left:87.6, top:7.2},
  {name:"Superbunny Cave (Bottom)", world:"dw", left:85.0, top:16.0},
  {name:"Dark Death Mountain Shop", world:"dw", left:87.6, top:16.0},
  {name:"Turtle Rock", world:"dw", left:95.4, top:9.0},
  {name:"Turtle Rock Isolated Ledge Entrance", world:"dw", left:83.4, top:13.0},
  {name:"Dark Death Mountain Ledge (West)", world:"dw", left:81.2, top:10.0},
  {name:"Dark Death Mountain Ledge (East)", world:"dw", left:85.8, top:10.0},
];